### ISSUE TITLE
repository is slow

### ISSUE THREAD

**Issue by Kidlike** [Monits/findbugs-plugin#15]
First of all thanks for your effort !

I am experiencing very slow downloads from these repositories
http://nexus.monits.com/content/repositories/

2mb download in about 1 minute or more.

Is it possible to move this repository to another host or an OSS host ?

Thanks

**Comment by jsotuyod** [comment]
Thanks for the report. I'll investigate the issue.

I'm looking into moving to `jcenter()` for release builds, since we are already using it for a bunch of other OSS. Snapshots I'm not so sure. Anyway, a 0.2.0 release is due, since it's been quite some time since we found any breaking issues.

I'll try to get it submitted during the next couple days, then it'll depend on their review process to approve it.

**Comment by Kidlike** [comment]
Cool. Thanks for the quick response !

**Comment by Kidlike** [comment]
Any updates on this?

Is it gonna be moved to central with the 0.2.0 release ?

**Comment by jsotuyod** [comment]
I've applied for jcenter to allow both releases and snapshots, but have not heard back yet.

I delayed the 2.0 release due to #16, once fixed I'll release it.

**Comment by jsotuyod** [comment]
2.0.0 [released to bintray](https://bintray.com/monits/monits-android/findbugs-plugin) waiting for it to be included in jcenter along snapshots.

**Comment by jsotuyod** [comment]
0.2.0 is in jcenter, new snapshots will be published there too!
