### ISSUE TITLE
Null annotation detection doesn't propagate class or package level annotations to private methods

### ISSUE THREAD

**Issue by pabad** [Monits/findbugs-plugin#9]
Let's say you define a new nul annotation:
```java
@Nonnull
@Target({ElementType.PACKAGE, ElementType.TYPE, ElementType.METHOD})
@TypeQualifierDefault({ElementType.METHOD, ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
public @interface DefaultNonNull {}
```

If you apply that annotation at package level or class level, it will work fine except for private methods.

Private methods will raise a warning stating that nullness of their parameter and return values is unknown. If you add the annotation directly on the method, the warning goes away, but that defeats the purpose of setting a package or class level default.

This only affects private methods. Public, package and protected methods work fine.

**Comment by jsotuyod** [comment]
That seems to be so by design, [check it out here](https://github.com/findbugsproject/findbugs/blob/fd7ec8b5cc0b1b143589674cdcdb901fa5dc0dda/findbugs/src/java/edu/umd/cs/findbugs/ba/jsr305/TypeQualifierApplications.java#L999).

I'm not sure for the reason behind this though, I can't seem to find a proper draft for the JSR (only [this](http://www.cs.umd.edu/~pugh/JSR-305.pdf)) which says nothing on private methods not inheriting defaults.

Maybe go ask the guys at [FindBugs](https://github.com/findbugsproject/findbugs/) themselves?
